{{- if .Values.cachePvcTemplates }}
{{- range .Values.cachePvcTemplates }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  {{if .storageClass }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
  {{if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .storage | quote }}
{{- end }}
{{- end }}