rollout:
  enabled: true
  previewServiceEnabled: true
  bluegreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
  - host: k8s.frontend.chatapp.local
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls: []