image:
  tag: "$image_tag"
rollout:
  enabled: true
  previewServiceEnabled: true
  bluegreen:
    autoPromotionEnabled: true
    scaleDownDelaySeconds: 30
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
