image:
  imageTag: latest

rollout:
  enabled: true
  previewServiceEnabled: true
  bluegreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30

ingress:
  enabled: true
  className: "nginx"
  hosts:
  - paths:
      - path: /
        pathType: ImplementationSpecific
  tls: []