injector:
  enabled: "True"
  defaultVaultAddress: "http://vault.vault.svc.cluster.local:8200"
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    pathType: Prefix
    activeService: true
    hosts:
      - host: vault.local
        paths: []