apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.name" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
data:
  enabled_plugins: |
    [rabbitmq_peer_discovery_k8s, rabbitmq_management].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = {{ include "rabbitmq.name" . }}-headless
    cluster_formation.k8s.hostname_suffix = .{{ include "rabbitmq.name" . }}-headless.{{ .Release.Namespace }}.svc.cluster.local
    queue_master_locator=min-masters
  {{- with .Values.configmap.additionalData }}
  {{ toYaml . | nindent 2 }}
  {{- end }}