apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.name" . }}-headless
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range $name, $svcPort := .Values.service.ports}}
    - name: {{$name}}
      port: {{ $svcPort }}
      targetPort: {{ $name }}
      protocol: TCP
  {{- end}}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}