apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq.serviceAccountName" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ include "rabbitmq.name" . }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.serviceAccount.automount }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
