apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rabbitmq.name" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "rabbitmq.headlessServiceName" . }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "rabbitmq.name" . }}-data
      labels:
        {{- include "rabbitmq.labels" . | nindent 8 }}
    spec:
      storageClassName: {{ .Values.pvcData.storageClassName }}
      accessModes:
        {{- toYaml .Values.pvcData.accessModes | nindent 8 }}
      resources:
        requests:
          storage: {{ .Values.pvcData.storage }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rabbitmq.labels" . | nindent 8 }}
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rabbitmq.serviceAccountName" . }}
      volumes:
        - name: rabbitmq-config
          configMap:
            name: {{ include "rabbitmq.name" . }}
            optional: false
            items:
              - key: enabled_plugins
                path: "enabled_plugins"
              - key: rabbitmq.conf
                path: "rabbitmq.conf"
        - name: rabbitmq-config-rw
          emptyDir: {}
      {{- with .Values.server.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
          {{- with .Values.server.env }}
            {{- toYaml . | nindent 12}}
          {{- end}}
          args:
          {{- if .Values.server.args }}
            {{- toYaml .Values.server.args | nindent 12 }}
          {{- else }}
            - sh
            - -c
            - cp /tmp/rabbitmq/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf && echo '' >> /etc/rabbitmq/rabbitmq.conf;
              cp /tmp/rabbitmq/enabled_plugins /etc/rabbitmq/enabled_plugins;
              exec rabbitmq-server
          {{- end }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /tmp/rabbitmq
            - name: {{ include "rabbitmq.name" . }}-data
              mountPath: "/var/lib/rabbitmq/mnesia"            
          ports:
          {{- range $name, $svcPort := .Values.service.ports}}
            - name: {{ $name }}
              containerPort: {{ $svcPort }}
              protocol: TCP
          {{- end }}
          {{- with .Values.server.livenessProbe}}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          {{- with .Values.server.readinessProbe}}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end}}
        {{- include "rabbitmq.sidecarContainers" . | nindent 8 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}