image:
  tag: "latest"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/chat-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []