image:
  tag: "latest"

rollout:
  enabled: true
  previewServiceEnabled: true
  bluegreen:
    autoPromotionEnabled: true
    scaleDownDelaySeconds: 30

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/chat-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []