ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: k8s.backend.chatapp.local
      paths:
        - path: "/chat-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []