# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: hungtran679/mt_chat-service
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "chat-service"
  vault.hashicorp.com/agent-inject-secret-chat-service: "kv/data/chat-service"
  vault.hashicorp.com/agent-inject-template-chat-service: |
    {{- with secret "kv/data/chat-service" -}}
    {{ .Data.data.content | base64Decode }}
    {{- end }}
  vault.hashicorp.com/agent-inject-file-chat-service: "/app/application.properties"

podLabels: {}

livenessProbe:
  tcpSocket:
    port: 8082
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 8082
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

pvc:
  enabled: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: k8s.backend.chatapp.local
      paths:
        - path: /chat-service
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}