image:
  imageTag: latest

app:
  replicaCount: 1
  nodeSelector:
    eks.amazonaws.com/nodegroup: app-node-group

rollout:
  enabled: true
  previewServiceEnabled: true
  bluegreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/chat-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []