image:
  imageTag: 1.0-cc4a306-7

app:
  replicaCount: 1

rollout:
  enabled: true
  previewServiceEnabled: true
  bluegreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/chat-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []