image:
  tag: "$image_tag"
job:
  enabled: true
  image:
    tag: "$job_image_tag"
rollout:
  enabled: true
  previewServiceEnabled: true
  bluegreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/user-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []
