{{- if .Values.ingestor.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otel-collector.ingestor.name" . }}
  labels:
    {{- include "otel-collector.ingestor.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ include "otel-collector.name" . }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- with .Values.ingestor.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.ingestor.serviceAccount.automount }}
automountServiceAccountToken: {{ .Values.ingestor.serviceAccount.automount }}
{{- end }}
{{- end }}
