apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.headlessServiceName" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range $name, $svcPort := .Values.service.ports}}
    - name: {{$name}}
      port: {{ $svcPort }}
      targetPort: {{ $name }}
      protocol: TCP
  {{- end}}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}