{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "mongodb.name" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 -}}
{{- end }}
