apiVersion: v2
name: backend
description: A Helm chart for meetingteam backend
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common