image:
  imageTag: latest

app:
  replicaCount: 1
  nodeSelector:
    eks.amazonaws.com/nodegroup: app-node-group

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/websocket-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []