# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hungtran679/mt_websocket-service
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "websocket-service"
  vault.hashicorp.com/agent-inject-secret-user-service: "kv/data/websocket-service"
  vault.hashicorp.com/agent-inject-template-user-service: |
    {{- with secret "kv/data/websocket-service" -}}
    {{ .Data.data.content | base64Decode }}
    {{- end }}
  vault.hashicorp.com/agent-inject-file-user-service: "application.properties"

podLabels: {}

livenessProbe:
  tcpSocket:
    port: 8084
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 8084
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

pvc:
  enabled: false

env:
  - name: CONFIG_PATH
    value: /vault/secrets/application.properties

service:
  type: ClusterIP
  port: 8084

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: k8s.backend.chatapp.local
      paths:
        - path: /websocket-service
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}