injector:
  enabled: "true"
  defaultVaultAddress: "http://vault.vault.svc.cluster.local:8200"
server:
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: null
  ingress:
    enabled: true
    ingressClassName: "nginx"
    pathType: Prefix
    activeService: true
    hosts:
      - host: vault.local
        paths: []