injector:
  enabled: "true"
  defaultVaultAddress: "http://vault.vault.svc.cluster.local:8200"
server:
  service:
    type: NodePort
    nodePort: 30082
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: "gp2"
  # ingress:
  #   enabled: true
  #   ingressClassName: "nginx"
  #   pathType: Prefix
  #   activeService: true
  #   hosts:
  #     - host: vault.local
  #       paths: []