image:
  imageTag: 1.0-07e1b92-4

app:
  replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/meeting-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []