image:
  imageTag: 1.0-957a7e1-2

app:
  replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/meeting-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []