image:
  imageTag: 1.0-3f7b6d3-2

app:
  replicaCount: 1

rollout:
  enabled: true
  previewServiceEnabled: true
  bluegreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/meeting-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []