image:
  imageTag: 1.0-707f93a-11

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: "/meeting-service/(?!.*/private/).*"
          pathType: ImplementationSpecific
  tls: []