controller: 
  serviceType: NodePort
  nodePort: 30808
  installPlugins: []
    # Kubernetes
    # Pipeline
    # Git
    # Configuration as Code Plugin
    # SonarQube Scanner
    # Github Branch Source

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: "gp2"
  size: "2Gi"

cachePvcTemplates:
  - name: jenkins-agent-cache-pvc
    storageClass: "efs-sc"
    accessModes:
      - ReadWriteMany
    storage: 6Gi

agent:
  kubernetesConnectTimeout: 5
  kubernetesReadTimeout: 15
  retentionTimeout: 30
  containerCap: 3 # Limit the numbers of launched agent pods
  idleMinutes: 10 # Limit the time an agent pod runs to 10 minutes
  podTemplates:
    springboot: |
      - name: springboot
        namespace: jenkins
        label: jenkins-maven
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            containers:
              - name: maven
                image: maven:3.9.6-eclipse-temurin-17-alpine
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: jenkins-cache
                    mountPath: /root/.m2
                    subPath: maven-repo
                  - name: jenkins-cache
                    mountPath: /root/.sonar/cache
                    subPath: sonar-cache
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                command:
                  - sleep
                  - infinity
                tty: true
              - name: trivy
                image: 'aquasec/trivy'
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: jenkins-cache
                    mountPath: /root/.cache/trivy
                    subPath: trivy-cache
            volumes:
              - name: jenkins-cache
                persistentVolumeClaim:
                  claimName: jenkins-agent-cache-pvc
    nodejs: |
      - name: nodejs
        namespace: jenkins
        label: jenkins-nodejs
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins
            containers:
              - name: nodejs
                image: 'node:18-alpine'
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: cache-volume
                    mountPath: /root/.npm
                    subPath: npm-cache
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                command:
                  - sleep
                  - infinity
                tty: true
              - name: sonar
                image: 'sonarsource/sonar-scanner-cli'
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: cache-volume
                    mountPath: /root/.sonar/cache
                    subPath: sonar-cache
                securityContext:
                  fsGroup: 1000
              - name: trivy
                image: 'aquasec/trivy'
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: cache-volume
                    mountPath: /root/.cache/trivy
                    subPath: trivy-cache
            volumes:
              - name: cache-volume
                persistentVolumeClaim:
                  claimName: jenkins-agent-cache-pvc
    k6: |
      - name: k6
        namespace: jenkins
        label: jenkins-k6
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins
            containers:
              - name: k6
                image: 'hungtran679/k6'
                command:
                  - sleep
                  - infinity
                tty: true
    terraform:  |
      - name: terraform
        namespace: jenkins
        label: jenkins-terraform
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins
            containers:
              - name: terraform
                image: 'hashicorp/terraform'
                command:
                  - sleep
                  - infinity
                tty: true
