controller:
  serviceType: NodePort
  nodePort: 30808
  installPlugins: []
    # - kubernetes:4296.v20a_7e4d77cf6
    # - pipeline:600.vb_57cdd26fdd7
    # - git:5.6.0
    # - configuration-as-code:1897.v79281e066ea_7
    # SonarQube Scanner
    # Mail Extension

persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  storageClass: "ebs-gp3"
  size: "1Gi"

agent:
  podTemplates:
    springboot: |
      - name: springboot
        namespace: jenkins
        label: jenkins-maven
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            containers:
              - name: maven
                image: maven:3.9.6-eclipse-temurin-17-alpine
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: maven-repo
                    mountPath: /root/.m2
                  - name: sonar-cache
                    mountPath: /root/.sonar/cache
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                command:
                  - sleep
                  - infinity
                tty: true
              - name: trivy
                image: aquasec/trivy
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: trivy-cache
                    mountPath: /root/.cache/trivy
            volumes:
              - name: maven-repo
                persistentVolumeClaim:
                  claimName: maven-pvc
              - name: sonar-cache
                persistentVolumeClaim:
                  claimName: sonar-cache-pvc        
              - name: trivy-cache
                persistentVolumeClaim:
                  claimName: trivy-cache-pvc     
    nodejs: |
      - name: nodejs
        namespace: jenkins
        label: jenkins-nodejs
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins
            containers:
              - name: nodejs
                image: 'node:18-alpine'
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: npm-cache
                    mountPath: /root/.npm
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                command:
                  - sleep
                  - infinity
                tty: true
              - name: trivy
                image: 'aquasec/trivy'
                command:
                  - sleep
                  - infinity
                tty: true
                volumeMounts:
                  - name: trivy-cache
                    mountPath: /root/.cache/trivy
            volumes:
              - name: npm-cache
                persistentVolumeClaim:
                  claimName: npm-cache-pvc
              - name: sonar-cache
                persistentVolumeClaim:
                  claimName: sonar-cache-pvc        
              - name: trivy-cache
                persistentVolumeClaim:
                  claimName: trivy-cache-pvc  
    k6: |
      - name: k6
        namespace: jenkins
        label: jenkins-k6
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins
            containers:
              - name: k6
                image: 'hungtran679/k6'
                command:
                  - sleep
                  - infinity
                tty: true


templateVpc:
  enabled: true
  storageClass: "ebs-gp3"
  vpcs:
    - name: maven-pvc
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
    - name: npm-cache-pvc
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
    - name: sonar-cache-pvc
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
    - name: trivy-cache-pvc
      accessModes:
        - ReadWriteOnce
      storage: 2Gi


