# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: hungtran679/mt_team-service
  tag: "v1.0"
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "team-service-role"
  vault.hashicorp.com/agent-inject-secret-user-service: "secret/team-service-secret"
  vault.hashicorp.com/agent-inject-template-user-service: |
    {{- with secret "secret/team-service-secret" -}}
    {{ .Data.data.content | base64Decode }}
    {{- end }}
  vault.hashicorp.com/agent-inject-file-user-service: "/app/application.properties"

podLabels: {}

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

pvc:
  enabled: false

job:
  enabled: true
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "user-service-flyway-role"
    vault.hashicorp.com/agent-inject-secret-flyway: "secret/user-service-flyway-secret"
    vault.hashicorp.com/agent-inject-template-flyway: |
      {{- with secret "secret/user-service-flyway-secret" -}}
      {{ .Data.data.content | base64Decode }}
      {{- end }}
    vault.hashicorp.com/agent-inject-file-flyway: "/flyway/conf/flyway.conf"
  imagePullSecrets: []
  image: "hungtran679/mt_flyway_user-service"
  tag: "latest"
  pullPolicy: IfNotPresent
  restartPolicy: OnFailure

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: k8s.backend.chatapp.local
      paths:
        - path: /team-service
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}