controller:
  nodeSelector:
    eks.amazonaws.com/nodegroup: system-node-group

server: 
  nodeSelector:
    eks.amazonaws.com/nodegroup: system-node-group
  service:
    type: NodePort
    nodePortHttp: 30081
  resources: {}
  ingress:
    enabled: false
    # ingressClassName: "nginx"
    # https: false
    # hosts:
    #   - argocd.local
    # paths:
    #   - /
    # pathType: Prefix